# Config file for automatic testing at travis-ci.org

sudo: required
language: minimal
services:
  - docker

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: docker-compose build

jobs:
  include:
    - stage: test
      # Command to run tests, e.g. python setup.py test
      script: docker-compose run app pytest
